### ISSUE TITLE
Discount

### ISSUE THREAD

**Issue by BenasB** [vu-omegapoint/pos-api#13]
Figure out how discounts should work from a business perspective and how they would fit into our payments and order technical implementation.

**Comment by RugileVa** [comment]
Process flow according to the specification:
**-** Discounts are applied by entering a transaction ID _(order)_ and a discount code. The system adjusts the sale _(order)_ total and records the discount application.

It is not specified whether one order can have only one discount, thus can allow discount to be combined.
Thus the order can have many discounts and one discount can be a part of many orders. 

Bellow a schema definition is provided. 
![image](https://github.com/vu-omegapoint/pos-api/assets/78092311/9d0ed2dc-79fd-44b6-8843-e6fb5b150993)
Maybe we could ship the percentage in discounts and only do fixed/absolute amounts? 

When the order is created or updated, the `total` field takes the discounts into account.

**Comment by BenasB** [comment]
> according to the specification

Do you mean the specification we received from the other team?

Because I don't see any "discount **code**"
![image](https://github.com/vu-omegapoint/pos-api/assets/29711974/f5fc821d-2ab3-469a-9925-73e576d36143)

**Comment by BenasB** [comment]
many-to-many relationship seems a bit overkill at this time

**Comment by BenasB** [comment]
Also I'm not sure if we're talking about global sales/discounts (something that a manager creates and is applied to everyone buying the product) or if we're talking about voucher/discount codes (a unique code that you can enter when paying to pay some amount or apply a discount/percentage off)

**Comment by BenasB** [comment]
I will implement this, at least we'll have something basic

**Comment by RugileVa** [comment]
It seems like the yaml specification differs from the process flow in the document :)

**Comment by BenasB** [comment]
okay, i'll do the unique codes
